services:
  engine:
    build: engine/.
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
     - "3000:3000"
    links:
     - db
    volumes:
     - ./assets:/usr/src/app/public/assets
     - ./log:/usr/src/app/log
  db:
    image: mongo:3
    volumes:
     - ./data:/data/db
version: '2'

